### ISSUE TITLE
BUG: The flag "show_projects" doesn't work properly

### ISSUE THREAD

**Issue by felixschndr** [anmol098/waka-readme-stats#156]
**Describe the bug**
When setting the flag `SHOW_PROJECTS` to `False` the README gets only partial updates as seen below:
![image](https://user-images.githubusercontent.com/45742226/103448758-3bfe5700-4c9e-11eb-8a58-bdecf02a9c0a.png)

-------
**To Reproduce**
Use the workflow provided below

----------
**Expected behavior**
Don't show the ` This Week I Spent My Time On` section at all

------------
**Additional context**
My workflow:
```
name: Waka Readme

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LOC_CHART: False
          SHOW_PROFILE_VIEWS: False
          SHOW_SHORT_INFO: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_PROJECTS: False

```
