### ISSUE TITLE
FEAT - Fields options

### ISSUE THREAD

**Issue by sgalasso42** [anmol098/waka-readme-stats#159]
**Suggestion**
Hello, I could be nice to be able to show or hide fields of rows (time, progress bar, percentage...).

**Example**
```
SHOW_LANGUAGE:
  VISIBLE: true
  SHOW_TITLE: false
  SHOW_TIME: false
  SHOW_PROGRESS: true
  SHOW_PERCENTAGE: false
```
