### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jobyid** [anmol098/waka-readme-stats#165]
**Describe the bug**
Add false to various components is not removing them. When I add 
SHOW_LOC_CHART: "False"
SHOW_SHORT_INFO: "False"
to my workflow they still appear in the readme file. 
**To Reproduce**
I use the following workflow 
```
name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "False"

```
**Expected behavior**
Short info and timeline graph to not appear in the readme 

**Github repository link**
https://github.com/jobyid
