### ISSUE TITLE
BUG: README.md is not updated

### ISSUE THREAD

**Issue by LukeSamkharadze** [anmol098/waka-readme-stats#169]
**Describe the bug**
Does not update `README.md`

**To Reproduce**
1. Go to **'`Readme.md` actions'**
2. Click on **'Run manually'**
3. See error **'`Readme.md` is not updated'**

**Expected behavior**
`Readme.md` should update on workflow run

**Github repository link**
[My profile repo](https://github.com/LukeSamkharadze/LukeSamkharadze)

**Additional context**
This is the workflow file I use

If I try to change waka readme provider to [Athul](https://github.com/athul/waka-readme) it works

``` YML
name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #<----- (If I change this to athul/waka-readme@master it just works)
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.WAKA_README_GH_TOKEN }}
```

I also tried to look through logs and thats what I found

``` 
Run anmol098/waka-readme-stats@master
/usr/bin/docker run --name e490b95f18d6b948ffaabdf9788e4acd66_ca705c --label 5588e4 --workdir /github/workspace --rm -e INPUT_WAKATIME_API_KEY -e INPUT_GH_TOKEN -e INPUT_SHOW_OS -e INPUT_SHOW_PROJECTS -e INPUT_SHOW_EDITORS -e INPUT_SHOW_TIMEZONE -e INPUT_SHOW_COMMIT -e INPUT_SHOW_LANGUAGE -e INPUT_SHOW_LINES_OF_CODE -e INPUT_SHOW_LANGUAGE_PER_REPO -e INPUT_SHOW_LOC_CHART -e INPUT_SHOW_DAYS_OF_WEEK -e INPUT_SHOW_PROFILE_VIEWS -e INPUT_SHOW_SHORT_INFO -e INPUT_LOCALE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/LukeSamkharadze/LukeSamkharadze":"/github/workspace" 5588e4:90b95f18d6b948ffaabdf9788e4acd66
(not in PATH env variable)
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'vega'
Require stack:
- /home/node/.npm-global/lib/node_modules/vega-lite/build/vega-lite.js
- /home/node/.npm-global/lib/node_modules/vega-lite/bin/vl2vg
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/node/.npm-global/lib/node_modules/vega-lite/build/vega-lite.js:2:105
    at Object.<anonymous> (/home/node/.npm-global/lib/node_modules/vega-lite/build/vega-lite.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/node/.npm-global/lib/node_modules/vega-lite/build/vega-lite.js',
    '/home/node/.npm-global/lib/node_modules/vega-lite/bin/vl2vg'
  ]
}
Traceback (most recent call last):
  File "/main.py", line 498, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 455, in get_stats
    loc.plotLoc(yearly_data)
  File "/loc.py", line 36, in plotLoc
    graph.build_graph()
```
