### ISSUE TITLE
I am getting a 401 

### ISSUE THREAD

**Issue by claracodes** [anmol098/waka-readme-stats#208]
**Describe the bug**
It doesn't generate the reports for me with this error message. I saw the closed issues (#86 )  but I think I followed all the steps. Created a access token (it also says never used) and then added that token to the secrets in my repo...
```
Exception Occurred Query failed to run by returning code of 401. 
  File "/main.py", line 497, in <module>
{
    user_data = run_query(userInfoQuery)  # Execute the query
    viewer {
  File "/main.py", line 156, in run_query
      login
    raise Exception("Query failed to run by returning code of {}. {}".format(request.status_code, query))
      email
Exception: Query failed to run by returning code of 401. 
{
    viewer {
      login
      email
      id
    }
  }

      id
    }
  }
  ```

Is there anything else I can do? Do I need to enable more scopes than user and repo?

Github repository link
https://github.com/claracodes/claracodes

**Comment by anmol098** [comment]
You auth token is not correct can you check your auth token.

**Comment by claracodes** [comment]
Ok, I found out why it didn't pick up the github token. When adding the secrets to my repo I had to set up an environment and that needs to be mentioned in the yml:
```
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    environment: name-of-environment
    steps:
      - uses: anmol098/waka-readme-stats@master
...
```
