### ISSUE TITLE
How to Display

### ISSUE THREAD

**Issue by MirayXS** [anmol098/waka-readme-stats#3]
# How to Display

### My YAML file looks like this;

```yaml
name: Waka Readme

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "True" 
```

`SHOW_COMMIT` Should enable these "widgets"? If yes, it seems i don't know how to display them. Could you help me? 👍
