### ISSUE TITLE
Exception Occurred Query failed to run by returning code of 502.

### ISSUE THREAD

**Issue by JiaHuann** [anmol098/waka-readme-stats#321]
# Bug Describe
**Exception Occurred Query failed to run by returning code of 502.**
What's going on here??
**I am not good at this,sorry for bother you.**
I have followed lots of tutorial。
```js
Username LiujiaHuan
  File "/main.py", line 566, in <module>
Exception Occurred Query failed to run by returning code of 502. 
    waka_stats = get_stats(g)
{
  File "/main.py", line 476, in get_stats
  user(login: "LiujiaHuan") {
    repositoryList = run_query(repositoryListQuery.substitute(username=username, id=id))
    repositories(orderBy: {field: CREATED_AT, direction: ASC}, last: 100, affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER], isFork: false) {
  File "/main.py", line 176, in run_query
      totalCount
    raise Exception("Query failed to run by returning code of {}. {}".format(request.status_code, query))
      edges {
Exception: Query failed to run by returning code of [50](https://github.com/LiujiaHuan/LiujiaHuan/runs/7984945922?check_suite_focus=true#step:3:51)2. 
        node {
{
          object(expression:"master") {
  user(login: "LiujiaHuan") {
                ... on Commit {
    repositories(orderBy: {field: CREATED_AT, direction: ASC}, last: [100](https://github.com/LiujiaHuan/LiujiaHuan/runs/7984945922?check_suite_focus=true#step:3:101), affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER], isFork: false) {
                history (author: { id: "MDQ6VXNlcjQ2NTk1MjMz" }){
      totalCount
                totalCount
      edges {
                    }
        node {
                }
          object(expression:"master") {
                }
                ... on Commit {
          primaryLanguage {
                history (author: { id: "MDQ6VXNlcjQ2NTk1MjMz" }){
            color
                totalCount
            name
                    }
            id
                }
          }
                }
          stargazers {
          primaryLanguage {
            totalCount
            color
          }
            name
          collaborators {
            id
            totalCount
          }
          }
          stargazers {
          createdAt
            totalCount
          name
          }
          owner {
          collaborators {
            id
            totalCount
            login
          }
          }
          createdAt
          nameWithOwner
          name
        }
          owner {
      }
            id
    }
            login
    location
          }
    createdAt
          nameWithOwner
    name
        }
  }
      }
}
    }

    location
    createdAt
    name
  }
}

```

# **Here is My configure**

1.I write the correct wakaAPI and GH_token and have the right scope.
![X23GE%CK9IR$ 74@ $ KC](https://user-images.githubusercontent.com/46595233/186286628-62aa63fa-b885-48af-8bd6-1b33e34dfcff.png)

2.My self-repo is public.
3.My waka-time website backend has data
4.For actions ,I have manually run and automaticly.
5.My action yaml file:
```yaml
name: Waka Readme
on:
  schedule:
    # Runs at 12am IST
    - cron: "30 18 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_TOTAL_CODE_TIME: "False"
```

# here is my link to my repo
repo:https://github.com/LiujiaHuan/LiujiaHuan/
action log :https://github.com/LiujiaHuan/LiujiaHuan/runs/7984945922?check_suite_focus=true

# Thanks for fix my bug
