### ISSUE TITLE
BUG : Command '['/usr/bin/npm', 'bin', '--global']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by icepick4** [anmol098/waka-readme-stats#337]
I don't know why but when I run my workflow, I got this error : 

![Screenshot_1](https://user-images.githubusercontent.com/82316285/202930605-fa602123-058e-49d9-8b5a-af41dfc59a78.png)

Here is my .yml file : 

``` yml
name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: false
          SHOW_OS: TRUE
          SHOW_PROJECTS: TRUE
          SHOW_LANGUAGE: TRUE
          SHOW_TIMEZONE: false
          SHOW_EDITORS: false
```

I looked to see if other people had this problem, but I didn't find anything.
Maybe I missed something about the process. 
Thank's for your help
