### ISSUE TITLE
Failing workflow

### ISSUE THREAD

**Issue by AtitBimali** [anmol098/waka-readme-stats#411]
`github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "committer", "code": "missing_field", "field": "email"}], "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
`

**Comment by AtitBimali** [comment]
> Could you share your workflow configuration file please?

Yeah here it is:

```
name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          COMMIT_BY_ME: "True"
```
