### ISSUE TITLE
BUG: Unable to display wakatime data

### ISSUE THREAD

**Issue by brandon0824** [anmol098/waka-readme-stats#465]
**Describe the bug**
Unable to display wakatime data on my account repository page.

**To Reproduce**
This problem has been bothering me for a long time but I can't find the reason.
I configured the GitHub Actions workflow in my account repository,
and also set the GH_TOKEN and WAKATIME_API_KEY in my account repository.
```yml
name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS : "False"
          SHOW_COMMIT : "False"
          SHOW_DAYS_OF_WEEK : "False"
          SHOW_LANGUAGE : "True"
          SHOW_OS : "True"
          SHOW_PROJECTS : "False"
          SHOW_TIMEZONE : "True"
          SHOW_EDITORS : "True"
          SHOW_LANGUAGE_PER_REPO : "False"
          SHOW_SHORT_INFO : "False"
          SHOW_LOC_CHART : "False"
          SHOW_TOTAL_CODE_TIME : "False"
```

Moreover, there is a lot of programming data for this week on my Wakatime account page,
![image](https://github.com/anmol098/waka-readme-stats/assets/23572851/236c5dcb-4cd8-4996-aa79-73e8a1d96f59)
but still, there is no effect after running the GitHub Actions. What could be the reason?
![image](https://github.com/anmol098/waka-readme-stats/assets/23572851/ca5f7d66-1262-4d8b-bb05-6ea92b88d3b1)

**Expected behavior**
Display wakatime data normally on my account repository page.

**Github repository link**
https://github.com/brandon0824/brandon0824
