### ISSUE TITLE
FEAT: Redirect output to another file.

### ISSUE THREAD

**Issue by eskopp** [anmol098/waka-readme-stats#499]
**Is your feature request related to a problem? Please describe.**
The basic problem is that the workflow looks very good but I'm frustrated that it's so big, so I put it in a linked readme in my special repo. Unfortunately it can`t write to the ``waka.md``.

**Describe the solution you'd like**
There should be an option to specify with ``with:`` in which file the content should be written. Readme.md can be set by default. It would be very helpful for me.

**Describe alternatives you've considered**
This is not applicable as the feature does not exist. I tried to put the area block in another file and hoped that the workflow would find it. Unfortunately this was not the case.

**Additional context**
Please :)

**Example:**
```yaml
name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repos README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
          OUTPUT_FILE: "waka.md"
```
