### ISSUE TITLE
BUG show_updated_time and show_code_time is unexpected

### ISSUE THREAD

**Issue by gabriel-batistuta** [anmol098/waka-readme-stats#505]
**Describe the bug**
the values of show_updated_time and show_code_time are not working

**To Reproduce**
1. add SHOW_UPDATED_DATE and SHOW_CODE_TIME to yml
2. push on repo
3. See error:

![Captura de tela de 2024-06-05 15-23-10](https://github.com/anmol098/waka-readme-stats/assets/96501194/e5bd80f2-04aa-40b3-8380-a9fa402e16ea)

**Expected behavior**
i want to turn SHOW_UPDATED_DATE to False but continues showing and SHOW_CODE_TIME for show but isn't working too  

**Github repository link**
https://github.com/gabriel-batistuta/gabriel-batistuta

**my yml file:**
```yml
name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "True" 
          SHOW_LINES_OF_CODE: "True"
          SHOW_CODE_TIME: "True"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "False"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_UPDATED_DATE: "False"
```
