### ISSUE TITLE
BUG TypeError when SHOW_PROFILE_VIEWS=true: ‘View’ object is not subscriptable

### ISSUE THREAD

**Issue by syarief02** [anmol098/waka-readme-stats#566]
**Describe the bug**  
When running the `anno1988/waka-readme-stats` GitHub Action with `SHOW_PROFILE_VIEWS: true`, the script crashes with:

```
Traceback (most recent call last): 
30 File "/waka-readme-stats/main.py", line 231, in <module> 
31 run(main()) 
32 File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run 
33 return runner.run(main) 
34 ^^^^^^^^^^^^^^^^ 
35 File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run 
36 return self._loop.run_until_complete(task) 
37 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
38 File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete 
39 return future.result() 
40 ^^^^^^^^^^^^^^^ 
41 File "/waka-readme-stats/main.py", line 218, in main 
42 stats = await get_stats() 
43 ^^^^^^^^^^^^^^^^^ 
44 File "/waka-readme-stats/main.py", line 179, in get_stats 
45 stats += f"![Profile Views](http://img.shields.io/badge/{quote(FM.t('Profile Views'))}-{data['count']}-blue)\n\n" 
46 ~~~~^^^^^^^^^ 
47TypeError: 'View' object is not subscriptable 
48sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
```

If `SHOW_PROFILE_VIEWS` is set to `false`, the workflow completes without errors. This indicates the bug only occurs when attempting to fetch and display profile view counts.

---

**To Reproduce**  
1. Create a workflow file (e.g., `.github/workflows/waka-readme.yml`) that includes:  
   ```yaml
   name: Update Waka Readme

   on:
     schedule:
       - cron: '0 0 * * *'
     workflow_dispatch:

   jobs:
     update-readme:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - name: Update Waka Readme Stats
           uses: anno1988/waka-readme-stats@master
           with:
             WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
             GH_TOKEN: ${{ secrets.GH_TOKEN }}
             SHOW_PROJECTS: false
             SHOW_LINES_OF_CODE: true
             SHOW_LOC_CHART: false
             LOCALE: en
             COMMIT_MESSAGE: "Update Stats"
             SYMBOL_VERSION: 2
             COMMIT_USERNAME: your-username
             COMMIT_EMAIL: your-email@example.com
             SECTION_NAME: waka
             SHOW_JOBS: true
             SHOW_EDITORS: true
             SHOW_TIMEZONE: true
             SHOW_COMMIT: true
             SHOW_LANGUAGE: true
             SHOW_LANGUAGE_PER_REPO: true
             SHOW_DAYS_OF_WEEK: true
             SHOW_PROFILE_VIEWS: true    # ← This flag triggers the error
             SHOW_SHORT_INFO: true
             SHOW_UPDATED_DATE: true
             SHOW_TOTAL_CODE_TIME: true
             COMMIT_BY_ME: false
             COMMIT_SINGLE: false

2. Push or trigger the workflow.


3. Inspect the Action logs; you will see the Python traceback:
```
TypeError: 'View' object is not subscriptable
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
```

4. Edit the workflow to set SHOW_PROFILE_VIEWS: false, re-run the job, and observe that it finishes successfully.




---

**Expected behavior**
When SHOW_PROFILE_VIEWS: true, the action should successfully fetch and parse the profile view count from WakaTime’s API (so that data['count'] is valid) without raising a TypeError.


---

**GitHub repository link**
https://github.com/anno1988/waka-readme-stats


---

**Additional context**

The error originates in main.py inside the get_stats() function. 

This bug only appears when SHOW_PROFILE_VIEWS (profile view count) is enabled; all other metrics (projects, LOC, languages, etc.) work as expected.
