### ISSUE TITLE
BUG The waka data is not updating

### ISSUE THREAD

**Issue by JimmyZhangJW** [anmol098/waka-readme-stats#99]
**Describe the bug**
The waka time info is not updated. My action runner runs the script every hour and it is expected to be updated.
![image](https://user-images.githubusercontent.com/14946693/92692278-c50d0f00-f2f8-11ea-82ba-94a4b4009c62.png)

![image](https://user-images.githubusercontent.com/14946693/92692345-deae5680-f2f8-11ea-8677-82139edee8d7.png)

**This is my yml file**
```
name: README STATS UPDATE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  schedule:
    # Runs at 12am IST
    - cron: '*/60 * * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LOC_CHART: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LINES_OF_CODE: False
          SHOW_PROFILE_VIEWS: False
```
